version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: demo-app:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    restart: unless-stopped

